apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: production
  labels:
    app: postgres
    component: database
spec:
  type: ClusterIP
  clusterIP: None        # headless — sem VIP, DNS por pod
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
