apiVersion: v1
kind: Service
metadata:
  name: encontros-tech
  namespace: production
  labels:
    app: encontros-tech
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: LoadBalancer
  selector:
    app: encontros-tech
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
